//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public System.Guid Id { get; set; }
        public System.DateTime PostDate { get; set; }
        public string Text { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid ReportId { get; set; }
    
        internal virtual User User { get; set; }
        internal virtual Report Report { get; set; }
    }
}
