//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Report()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public System.Guid Id { get; set; }
        public string Text { get; set; }
        public string Title { get; set; }
        public System.DateTime CreationDate { get; internal set; }
        public System.DateTime LastUpdateDate { get; internal set; }
        public System.Guid CreatorId { get; set; }
        public System.Guid AssigneeId { get; set; }
    
        internal virtual User Creator { get; set; }
        internal virtual User Assignee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        internal virtual ICollection<Comment> Comments { get; set; }
    }
}
